In [1]:
import numpy as np
import pandas as pd

In [2]:
df1 = pd.read_csv("IBM Dataset.csv")
df1.head()

Age Attrition     BusinessTravel  DailyRate              Department  \
0   41       Yes      Travel_Rarely       1102                   Sales   
1   49        No  Travel_Frequently        279  Research & Development   
2   37       Yes      Travel_Rarely       1373  Research & Development   
3   33        No  Travel_Frequently       1392  Research & Development   
4   27        No      Travel_Rarely        591  Research & Development   

   DistanceFromHome  Education EducationField  EmployeeCount  EmployeeNumber  \
0                 1          2  Life Sciences              1               1   
1                 8          1  Life Sciences              1               2   
2                 2          2          Other              1               4   
3                 3          4  Life Sciences              1               5   
4                 2          1        Medical              1               7   

   ...  RelationshipSatisfaction StandardHours  StockOptionLevel  \
0  ...                         1            80                 0   
1  ...                         4            80                 1   
2  ...                         2            80                 0   
3  ...                         3            80                 0   
4  ...                         4            80                 1   

   TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  YearsAtCompany  \
0                  8                      0               1               6   
1                 10                      3               3              10   
2                  7                      3               3               0   
3                  8                      3               3               8   
4                  6                      3               3               2   

  YearsInCurrentRole  YearsSinceLastPromotion  YearsWithCurrManager  
0                  4                        0                     5  
1                  7                        1                     7  
2                  0                        0                     0  
3                  7                        3                     0  
4                  2                        2                     2  

[5 rows x 35 columns]

In [3]:
df1.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

In [4]:
ms = df1['MonthlyIncome']
age = df1['Age']
dist = df1['DistanceFromHome']
twy = df1['TotalWorkingYears']
yac = df1['YearsAtCompany']
yicr = df1['YearsInCurrentRole']
ywcm = df1['YearsWithCurrManager']


In [5]:
Y = df1['Attrition']

In [6]:
df1.drop(['Age', 'DistanceFromHome', 'TotalWorkingYears', 'YearsAtCompany', 'YearsInCurrentRole', 'YearsWithCurrManager', 'EmployeeCount','EmployeeNumber','Over18','RelationshipSatisfaction','StandardHours', 'Attrition', 'MonthlyIncome', 'BusinessTravel', 'DailyRate', 'Department', 'Education',
       'EducationField','Gender', 'HourlyRate', 'MonthlyRate', 'NumCompaniesWorked', 'PercentSalaryHike', 'PerformanceRating', 'TrainingTimesLastYear', 'WorkLifeBalance', 'YearsSinceLastPromotion'], axis = 1, inplace = True)
df1.head()

EnvironmentSatisfaction  JobInvolvement  JobLevel                JobRole  \
0                        2               3         2        Sales Executive   
1                        3               2         2     Research Scientist   
2                        4               2         1  Laboratory Technician   
3                        4               3         1     Research Scientist   
4                        1               3         1  Laboratory Technician   

   JobSatisfaction MaritalStatus OverTime  StockOptionLevel  
0                4        Single      Yes                 0  
1                2       Married       No                 1  
2                3        Single      Yes                 0  
3                3       Married      Yes                 0  
4                2       Married       No                 1

In [7]:
df1.columns

Index(['EnvironmentSatisfaction', 'JobInvolvement', 'JobLevel', 'JobRole',
       'JobSatisfaction', 'MaritalStatus', 'OverTime', 'StockOptionLevel'],
      dtype='object')

In [8]:
from sklearn.preprocessing import LabelEncoder
for column in df1.columns:
    if df1[column].dtype == np.number:
        continue
    df1[column] = LabelEncoder().fit_transform(df1[column]) 

C:\Users\raman\AppData\Local\Temp/ipykernel_20068/1978354428.py:3: DeprecationWarning: Converting `np.inexact` or `np.floating` to a dtype is deprecated. The current result is `float64` which is not strictly correct.
  if df1[column].dtype == np.number:
C:\Users\raman\AppData\Local\Temp/ipykernel_20068/1978354428.py:3: DeprecationWarning: Converting `np.inexact` or `np.floating` to a dtype is deprecated. The current result is `float64` which is not strictly correct.
  if df1[column].dtype == np.number:
C:\Users\raman\AppData\Local\Temp/ipykernel_20068/1978354428.py:3: DeprecationWarning: Converting `np.inexact` or `np.floating` to a dtype is deprecated. The current result is `float64` which is not strictly correct.
  if df1[column].dtype == np.number:
C:\Users\raman\AppData\Local\Temp/ipykernel_20068/1978354428.py:3: DeprecationWarning: Converting `np.inexact` or `np.floating` to a dtype is deprecated. The current result is `float64` which is not strictly correct.
  if df1[column].dtyp

In [9]:
df1['MonthlyIncome'] = ms
df1['Age'] = age
df1['DistanceFromHome'] = dist
df1['TotalWorkingYears'] = twy
df1['YearsAtCompany'] = yac
df1['YearsInCurrentRole'] = yicr
df1['YearsWithCurrManager'] = ywcm

In [10]:
x = df1
x.head(3)

EnvironmentSatisfaction  JobInvolvement  JobLevel  JobRole  \
0                        1               2         1        7   
1                        2               1         1        6   
2                        3               1         0        2   

   JobSatisfaction  MaritalStatus  OverTime  StockOptionLevel  MonthlyIncome  \
0                3              2         1                 0           5993   
1                1              1         0                 1           5130   
2                2              2         1                 0           2090   

   Age  DistanceFromHome  TotalWorkingYears  YearsAtCompany  \
0   41                 1                  8               6   
1   49                 8                 10              10   
2   37                 2                  7               0   

   YearsInCurrentRole  YearsWithCurrManager  
0                   4                     5  
1                   7                     7  
2                   0                     0

In [11]:
x.columns

Index(['EnvironmentSatisfaction', 'JobInvolvement', 'JobLevel', 'JobRole',
       'JobSatisfaction', 'MaritalStatus', 'OverTime', 'StockOptionLevel',
       'MonthlyIncome', 'Age', 'DistanceFromHome', 'TotalWorkingYears',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsWithCurrManager'],
      dtype='object')

In [12]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit(Y)
Y = le.transform(Y)

In [13]:
from sklearn.feature_selection import SelectKBest,f_classif
from sklearn.feature_selection import chi2

In [14]:
selector = SelectKBest(f_classif, k=15)
X_new_1 = selector.fit_transform(x, Y)

In [15]:
selected_features_1 = selector.get_support(indices = True)
selected_features_1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
      dtype=int64)

In [16]:
df2 = df1
df2.head()

EnvironmentSatisfaction  JobInvolvement  JobLevel  JobRole  \
0                        1               2         1        7   
1                        2               1         1        6   
2                        3               1         0        2   
3                        3               2         0        6   
4                        0               2         0        2   

   JobSatisfaction  MaritalStatus  OverTime  StockOptionLevel  MonthlyIncome  \
0                3              2         1                 0           5993   
1                1              1         0                 1           5130   
2                2              2         1                 0           2090   
3                2              1         1                 0           2909   
4                1              1         0                 1           3468   

   Age  DistanceFromHome  TotalWorkingYears  YearsAtCompany  \
0   41                 1                  8               6   
1   49                 8                 10              10   
2   37                 2                  7               0   
3   33                 3                  8               8   
4   27                 2                  6               2   

   YearsInCurrentRole  YearsWithCurrManager  
0                   4                     5  
1                   7                     7  
2                   0                     0  
3                   7                     0  
4                   2                     2

In [17]:
from sklearn import linear_model
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test=train_test_split(X_new_1 , Y, test_size = 0.20, random_state = 10)

In [18]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators = 100, random_state = 42)

In [19]:
model.fit(X_train,Y_train)

RandomForestClassifier(random_state=42)

In [20]:
pred = model.predict(X_test)

In [21]:
from sklearn import metrics
acc=metrics.accuracy_score(Y_test,pred)
acc

0.8503401360544217

In [22]:
from sklearn import svm
clf = svm.SVC(kernel = 'linear', C = 1.0)
clf.fit(X_train, Y_train)

SVC(kernel='linear')

In [23]:
pred1 = clf.predict(X_test)

In [24]:
acc1 = metrics.accuracy_score(Y_test,pred1)
acc1

0.8503401360544217

In [25]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train, Y_train)

GaussianNB()

In [26]:
pred2 = clf.predict(X_test)

In [27]:
acc2=metrics.accuracy_score(Y_test,pred2)
acc2

0.8503401360544217

In [28]:
clf.predict([[31,7,2,1,1,6,1,1,682,0,1,10,10,7,7]])

array([0])

In [29]:
import pickle
with open('naivebayes_pickle.pkl', 'wb') as files:
    pickle.dump(gnb, files)

In [30]:
pickled_model = pickle.load(open('naivebayes_pickle.pkl','rb'))

In [31]:
pickled_model.predict([[31,7,2,1,1,6,1,1,682,0,1,10,10,7,7]])

array([1])