In [34]:
import numpy as np 
import pandas as pd

In [2]:
df = pd.read_csv("IBM Dataset.csv")

In [3]:
Y=df['Attrition']

In [4]:
df.drop(['EmployeeCount','EmployeeNumber','Over18','RelationshipSatisfaction','StandardHours','Attrition'],1,inplace=True)

C:\Users\raman\AppData\Local\Temp/ipykernel_18276/3970810646.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  df.drop(['EmployeeCount','EmployeeNumber','Over18','RelationshipSatisfaction','StandardHours','Attrition'],1,inplace=True)


In [5]:
X=df

In [6]:
X

Age     BusinessTravel  DailyRate              Department  \
0      41      Travel_Rarely       1102                   Sales   
1      49  Travel_Frequently        279  Research & Development   
2      37      Travel_Rarely       1373  Research & Development   
3      33  Travel_Frequently       1392  Research & Development   
4      27      Travel_Rarely        591  Research & Development   
...   ...                ...        ...                     ...   
1465   36  Travel_Frequently        884  Research & Development   
1466   39      Travel_Rarely        613  Research & Development   
1467   27      Travel_Rarely        155  Research & Development   
1468   49  Travel_Frequently       1023                   Sales   
1469   34      Travel_Rarely        628  Research & Development   

      DistanceFromHome  Education EducationField  EnvironmentSatisfaction  \
0                    1          2  Life Sciences                        2   
1                    8          1  Life Sciences                        3   
2                    2          2          Other                        4   
3                    3          4  Life Sciences                        4   
4                    2          1        Medical                        1   
...                ...        ...            ...                      ...   
1465                23          2        Medical                        3   
1466                 6          1        Medical                        4   
1467                 4          3  Life Sciences                        2   
1468                 2          3        Medical                        4   
1469                 8          3        Medical                        2   

      Gender  HourlyRate  ...  PercentSalaryHike  PerformanceRating  \
0     Female          94  ...                 11                  3   
1       Male          61  ...                 23                  4   
2       Male          92  ...                 15                  3   
3     Female          56  ...                 11                  3   
4       Male          40  ...                 12                  3   
...      ...         ...  ...                ...                ...   
1465    Male          41  ...                 17                  3   
1466    Male          42  ...                 15                  3   
1467    Male          87  ...                 20                  4   
1468    Male          63  ...                 14                  3   
1469    Male          82  ...                 12                  3   

     StockOptionLevel  TotalWorkingYears TrainingTimesLastYear  \
0                   0                  8                     0   
1                   1                 10                     3   
2                   0                  7                     3   
3                   0                  8                     3   
4                   1                  6                     3   
...               ...                ...                   ...   
1465                1                 17                     3   
1466                1                  9                     5   
1467                1                  6                     0   
1468                0                 17                     3   
1469                0                  6                     3   

      WorkLifeBalance  YearsAtCompany  YearsInCurrentRole  \
0                   1               6                   4   
1                   3              10                   7   
2                   3               0                   0   
3                   3               8                   7   
4                   3               2                   2   
...               ...             ...                 ...   
1465                3               5                   2   
1466                3               7                   7   
1467                3               6                   2   
1468                

In [7]:
from sklearn.preprocessing import LabelEncoder
for column in X.columns:
    if X[column].dtype == np.number:
        continue
    X[column] = LabelEncoder().fit_transform(X[column]) 

C:\Users\raman\AppData\Local\Temp/ipykernel_18276/559448619.py:3: DeprecationWarning: Converting `np.inexact` or `np.floating` to a dtype is deprecated. The current result is `float64` which is not strictly correct.
  if X[column].dtype == np.number:
C:\Users\raman\AppData\Local\Temp/ipykernel_18276/559448619.py:3: DeprecationWarning: Converting `np.inexact` or `np.floating` to a dtype is deprecated. The current result is `float64` which is not strictly correct.
  if X[column].dtype == np.number:
C:\Users\raman\AppData\Local\Temp/ipykernel_18276/559448619.py:3: DeprecationWarning: Converting `np.inexact` or `np.floating` to a dtype is deprecated. The current result is `float64` which is not strictly correct.
  if X[column].dtype == np.number:
C:\Users\raman\AppData\Local\Temp/ipykernel_18276/559448619.py:3: DeprecationWarning: Converting `np.inexact` or `np.floating` to a dtype is deprecated. The current result is `float64` which is not strictly correct.
  if X[column].dtype == np.numb

In [8]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit(Y)
Y = le.transform(Y)

In [9]:
from sklearn.feature_selection import SelectKBest,f_classif
from sklearn.feature_selection import chi2


In [10]:
selector = SelectKBest(f_classif, k=15)
X_new_1 = selector.fit_transform(X, Y)

In [11]:
selected_features_1 = selector.get_support(indices=True)

In [12]:
selected_features_1

array([ 0,  4,  7, 10, 11, 12, 13, 14, 15, 18, 21, 22, 25, 26, 28],
      dtype=int64)

In [13]:
df1=df.iloc[:, [0,  4,  7, 10, 11, 12, 13, 14, 15, 18, 21, 22, 25, 26, 28 ]]
df1

Age  DistanceFromHome  EnvironmentSatisfaction  JobInvolvement  \
0      23                 0                        1               2   
1      31                 7                        2               1   
2      19                 1                        3               1   
3      15                 2                        3               2   
4       9                 1                        0               2   
...   ...               ...                      ...             ...   
1465   18                22                        2               3   
1466   21                 5                        3               1   
1467    9                 3                        1               3   
1468   31                 1                        3               1   
1469   16                 7                        1               3   

      JobLevel  JobRole  JobSatisfaction  MaritalStatus  MonthlyIncome  \
0            1        7                3              2            809   
1            1        6                1              1            682   
2            0        2                2              2             62   
3            0        6                2              1            313   
4            0        2                1              1            399   
...        ...      ...              ...            ...            ...   
1465         1        2                3              1            210   
1466         2        0                0              1           1070   
1467         1        4                1              1            821   
1468         1        7                1              1            730   
1469         1        2                2              1            554   

      OverTime  StockOptionLevel  TotalWorkingYears  YearsAtCompany  \
0            1                 0                  8               6   
1            0                 1                 10              10   
2            1                 0                  7               0   
3            1                 0                  8               8   
4            0                 1                  6               2   
...        ...               ...                ...             ...   
1465         0                 1                 17               5   
1466         0                 1                  9               7   
1467         1                 1                  6               6   
1468         0                 0                 17               9   
1469         0                 0                  6               4   

      YearsInCurrentRole  YearsWithCurrManager  
0                      4                     5  
1                      7                     7  
2                      0                     0  
3                      7                     0  
4                      2                     2  
...                  ...                   ...  
1465                   2                     3  
1466                   7                     7  
1467                   2                     3  
1468                   6                     8  
1469                   3                     2  

[1470 rows x 15 columns]

In [14]:
from sklearn import linear_model
from sklearn.model_selection import train_test_split

In [15]:
X_train,X_test,Y_train,Y_test=train_test_split(X_new_1,Y,test_size=0.20,random_state=10)

In [16]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(n_estimators=250, random_state=79)

In [17]:
model.fit(X_train,Y_train)

RandomForestClassifier(n_estimators=250, random_state=79)

In [18]:
pred=model.predict(X_test)

In [19]:
from sklearn import metrics
acc=metrics.accuracy_score(Y_test,pred)
acc

0.8537414965986394

In [20]:
from sklearn import svm

In [21]:
clf = svm.SVC(kernel='linear', C=1.0)

In [22]:
clf.fit(X_train,Y_train)

SVC(kernel='linear')

In [23]:
pred1=clf.predict(X_test)

In [24]:
acc1=metrics.accuracy_score(Y_test,pred1)
acc1

0.8129251700680272

In [25]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train, Y_train)

GaussianNB()

In [26]:
pred2=clf.predict(X_test)

In [27]:
acc2=metrics.accuracy_score(Y_test,pred2)
acc2

0.8129251700680272

In [28]:
clf.predict([[31,7,2,1,1,6,1,1,682,0,1,10,10,7,7]])

array([0])

In [29]:
import pickle

with open('naivebayes_pickle.pkl', 'wb') as files:
    pickle.dump(gnb, files)

# file = open('naivebayes_pickle.pkl', 'wb')
# pickle.dump(gnb, file)

In [30]:
pickled_model = pickle.load(open('naivebayes_pickle.pkl','rb'))

In [31]:
#prediction
pickled_model.predict([[31,7,2,1,1,6,1,1,682,0,1,10,10,7,7]])

array([0])

In [32]:
### new cell

In [33]:
import os
os.getcwd()

'c:\\Users\\raman\\Data Science\\eap_new'